apiVersion: v1
kind: Pod
metadata:
  name: pod-with-limits
  namespace: production
spec:
  containers:
    - name: container-with-limits
      image: nginx
      resources:
        limits:
          memory: "1Gi"
          cpu:    "100m"
        requests:
          memory: "1Gi"
          cpu:    "100m"

